---
title: "XDPFlyModel"
author: "Minjue Wu"
date: "12/12/2019"
output: html_document
---
###Modeling X-linked Dystonia Parkinsonism Via A Novel Fly Model — 

```{r loading, include=FALSE}
library(lubridate)
library(ggplot2)
library(gganimate)
library(janitor)
library(animation)
library(magick)
library(readxl)
library(knitr)
library(tidyverse)
library(dplyr)
library(gt)
library(tidyr)
library(mapdata)
```

```{r statveri, include = FALSE}
dir.create("statdata")

#This database contains four weeks of fly model data, including target genes, sorter, weekday, number of surviving flies, phenotype, and sizes of the right and left eye of every mutant fly. I gathered the dataset and cleaned it from scratch, as the datasheets used by the student researchers were completely unusable for code processing purposes. 

#Read in stats data sheets

f923p <- read_xlsx("statdata/923fly.xlsx") %>% 
  mutate(week = 0923)

f930p <- read_xlsx("statdata/930fly.xlsx") %>% 
  mutate(week = 0930)

f106p <- read_xlsx("statdata/106fly.xlsx") %>% 
  mutate(week = 1006)

f1013p <- read_xlsx("statdata/1013fly.xlsx") %>% 
  mutate(week = 1013)

#clear away datasets that have 0s as this should only record units of flies

mfp <- rbind(f923p, f930p, f106p, f1013p) %>%
  filter(amt != 0) 

#Calculate viability data for each vial and each gene every week (controls are repeated, so need to differentiate by week). 

viabilitygene <- mfp %>%
  group_by(week, gene, vial) %>%
  mutate(vialsum = sum(amt)) %>% 
  group_by(week, gene) %>%
  mutate(genesum = sum(amt))
 
viabilitygene <- viabilitygene %>%
  filter(knockdown == "T") %>%
  group_by(week, gene, vial) %>% 
  mutate(knockvial = sum(amt)) %>%
  group_by(week, gene) %>%
  mutate(knockgene = sum(amt)) 

#Calculate the percent viability for each vial and each gene

viabilitygene <- viabilitygene %>%
  mutate(pknockvial = 100*round(knockvial/vialsum, digits = 4)) %>%
  mutate(pknockgene = 100*round(knockgene/genesum, digits = 4)) 

view(viabilitygene)

#Generate table of statistics for each gene for verification of functional code later 

viabilitygene %>% select(gene, pknockgene) %>% unique()

```

```{r setup, echo = F}
dir.create("rawdata")

f923 <- read_xlsx("rawdata/923fly1.xlsx") %>% 
  mutate(week = 0923)

f930 <- read_xlsx("rawdata/930fly1.xlsx") %>% 
  mutate(week = 0930)

f106 <- read_xlsx("rawdata/106fly1.xlsx") %>% 
  mutate(week = 1006)

f1013 <- read_xlsx("rawdata/1013fly1.xlsx") %>% 
  mutate(week = 1013)

mf <- rbind(f923, f930, f106, f1013) %>%
  mutate(pathway = "CMAP Hit") %>%
  na.omit

#Add gene pathway significance

mf$pathway <- as.character(mf$pathway)

mf$pathway[mf$gene == "ATF2" |
          mf$gene ==  "XBP1" |
          mf$gene == "EIF2AK3/PERK"] <- "ER Stress"

mf$pathway[mf$gene == "HIF1A" |
             mf$gene ==  "MAPK1" |
             mf$gene == "P4HA1"] <- "Oxidative Stress" 

mf$pathway[mf$gene == "RELB" |
             mf$gene ==  "TRAF6"] <- "NFkB" 

view(mf)

mf$gene[mf$week == 923 & mf$gene == "control"] <- "control wk1" 
mf$gene[mf$week == 930 & mf$gene == "control"] <- "control wk2" 
mf$gene[mf$week == 106 & mf$gene == "control"] <- "control wk3" 
mf$gene[mf$week == 1013 & mf$gene == "control" & mf$analyst == "TS"] <- "control wk4.1" 
mf$gene[mf$week == 1013 & mf$gene == "control" & mf$analyst == "PD"] <- "control wk4.2" 


view(mf)
```

```{r allgenes, echo=F}
ggplot(mf, aes(fill = sex, x = gene)) + geom_bar() + theme(axis.text.x = element_text(angle = 90))
ggplot(mf, aes(fill = knockdown, x = gene)) + geom_bar() + theme(axis.text.x = element_text(angle = 90))

ggplot(mf, aes(fill = knockdown, x = gene, color = sex)) + geom_bar(position = position_dodge()) + theme(axis.text.x = element_text(angle = 90)) + scale_fill_brewer(palette="Greens") + theme_minimal() + theme(axis.text.x = element_text(angle = 90))

```


```{r eyecorrelation, echo = F}
mf %>%
  filter(knockdown == "T") %>%
  ggplot(aes(x = right, y = left)) + geom_point(shape = ".") + geom_jitter(aes(colour = gene, shape = pathway)) + geom_smooth(method = "lm") + theme(
    panel.background = element_rect(
      fill = "white",
      colour = "black",
      size = 0.5,
      linetype = "solid",
      color = "black"
    )
  ) + geom_hline(yintercept = c(0.5, 1.5, 2.5, 3.5), linetype = "dashed")  + geom_vline(xintercept = c(0.5, 1.5, 2.5, 3.5), linetype =                                        "dashed")  + theme(legend.position = "bottom", legend.box = "vertical")

vialbility <- mf %>%
  group_by(week, gene, vial) %>%
  mutate(vialsum = n()) %>%
  group_by(week, gene, vial, knockdown) %>%
  mutate(kovialsum = n()) %>%
  filter(knockdown == "F") %>%
  select(date, gene, vial, right, left, vialsum, kovialsum, pathway) %>%
  mutate(viability = 100*round((vialsum - kovialsum)/vialsum, digits = 4)) %>%
  unique() %>%
  view() 

ggplot(vialbility, aes(x = gene, y = viability, color = pathway)) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90))+ labs(title = "Viability of Knockdown Gene by Fly Proportions Per Vial", x = "Knockdown Gene", y = "Viability (% Mutant Fly/Vial Total)", color = "Pathway")


vialbility2 <- mf %>%
  group_by(date, gene, vial) %>%
  mutate(vialsum = n()) %>%
  group_by(date, gene, vial, knockdown) %>%
  mutate(kovialsum = n()) %>%
  filter(knockdown == "F") %>%
  select(date, gene, vial, right, left, vialsum, kovialsum, pathway) %>%
  mutate(viability = 100*round((vialsum - kovialsum)/vialsum, digit = 4)) %>%
  unique() 

ggplot(vialbility2, aes(x = date, y = viability)) + geom_point() + geom_jitter() + geom_smooth(method = "lm") + ylim(0,100) + labs(title = "Changes in Viability Over Time", subtitle = "",caption = "Viability calculated for flies counted per vial each day from all gene knockdowns.")
```

```{r mappingxdp}
library(maps)

phil <- map_data("world", region = "Philippines")

view(phil)

ggplot(data = phil, aes(x = long, y = lat, group = region)) + scale_fill_viridis_d() + geom_polygon(aes(group = group, fill = subregion)) + theme(legend.position = "none")

```

```{r correlation}
library(corrplot)
mf2 <- mf 
mf2$weekday[mf2$weekday == "M" ] <- 1
mf2$weekday[mf2$weekday == "T" ] <- 2
mf2$weekday[mf2$weekday == "W" ] <- 3
mf2$weekday[mf2$weekday == "H" ] <- 4
mf2$weekday[mf2$weekday == "F" ] <- 5

mf2$sex[mf2$sex == "F" ] <- 1
mf2$sex[mf2$sex == "M" ] <- 0

mf2 <- mf2 %>%
  mutate(survival = knockdown)

mf2$survival[mf2$knockdown == "T" ] <- 1
mf2$survival[mf2$knockdown == "F" ] <- 0

mf2$iser[mf2$pathway == "ER Stress" ] <- 1
mf2$iser[mf2$pathway != "ER Stress" ] <- 0
mf2$isos[mf2$pathway == "Oxidative Stress" ] <- 1
mf2$isos[mf2$pathway != "Oxidative Stress" ] <- 0
mf2$isnfkb[mf2$pathway == "NFkB" ] <- 1
mf2$isnfkb[mf2$pathway != "NFkB" ] <- 0

mf2 <- mf2 %>%
  select(weekday, sex, survival, left, right, iser, isos, isnfkb) %>%
  transform(sex = as.numeric(sex), survival = as.numeric(survival), weekday = as.numeric(weekday))

view(mf2)

res <- cor(mf2, use = "complete.obs")

col1 <- colorRampPalette(c("#7F0000", "red", "#FF7F00", "yellow", "white",
                           "cyan", "#007FFF", "blue", "#00007F"))
col2 <- colorRampPalette(c("#67001F", "#B2182B", "#D6604D", "#F4A582",
                           "#FDDBC7", "#FFFFFF", "#D1E5F0", "#92C5DE",
                           "#4393C3", "#2166AC", "#053061"))
col3 <- colorRampPalette(c("red", "white", "blue")) 
col4 <- colorRampPalette(c("#7F0000", "red", "#FF7F00", "yellow", "#7FFF7F",
                           "cyan", "#007FFF", "blue", "#00007F"))


corrplot(res, type = "lower", order = "hclust", method = "ellipse", tl.cex = 1, tl.col = "black", tl.srt = 45,addrect = 2, col = col1(100), title = "
         Correlation Between Eye Size, Survival, Weekday, and Pathways")
```

